menu:
    Blog: /
    About: /about
    Archive: /archives/
    GitHub: https://github.com/patrickbolle
    Rss: /atom.xml

favicon: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65909734-1

# Copyright Infomation
startyear: 2016

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: yes
