# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Build A Shopify Store: /shopify

# Logo Image Source

# Theme Main Subtitle
subtitle_main: web development portfolio and blog

# Theme Secondary subtitle
susbtitle_secondary: Recently graduated computer programmer/web freelancer living in Canada. I travel a lot, write music and code.<br> View my portfolio and find out more about me <a href="/about">here.</a>

# Footer About Section
about_footer: Built by Patrick Bollenbach using <a href="http://hexo.io">Hexo</a>

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "https://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: patrickbollenbach

  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-65909734-1

# Social Accounts
twitter_url: https://twitter.com/patrickbolle
linkedin_url: https://linkedin.com/patrickbolle
github_url: https://github.com/patrickbolle
email_url: mailto:patrickbollenbachcc@gmail.com
rss_url: \#
